requires:
- category: "development"
  name: "toolchain"
  version: ">=0"


env:
- CFLAGS="-D_GNU_SOURCE -I/include -I/usr/include -fPIC"
- LDFLAGS="-L/usr/lib -L/lib"

package_dir: /{{.Values.name}}
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf development/make development/automake vcs/git development/m4 libs/libressl && \
   mkdir -p /${PACKAGE_NAME} && mkdir ${PACKAGE_NAME} && \
   wget https://www.netfilter.org/pub/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.bz2 -O ${PACKAGE_NAME}.tar.bz2 && tar -xvf ${PACKAGE_NAME}.tar.bz2 -C ./ && mv ${PACKAGE_NAME}-$PACKAGE_VERSION ${PACKAGE_NAME}
steps:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   cd ${PACKAGE_NAME}/${PACKAGE_NAME}-$PACKAGE_VERSION  && ./configure --prefix=/usr  && \
   make -j8  && \
   make DESTDIR=/${PACKAGE_NAME} install && \
   make install
