requires:
- category: development
  name: cmake
  version: ">=0"
env:
- CFLAGS="-I/include -I/usr/include"
- REAL_PACKAGE_NAME=libjpeg
- PACKAGE_COMMIT=6c0fcb8ddee365e7abc4d332662b06900612e923

package_dir: /libjpeg
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${REAL_PACKAGE_NAME} && \
   luet install shells/bash development/make utils/ca-certificates libs/libressl vcs/git && \
   git clone https://github.com/LuaDist/libjpeg ${REAL_PACKAGE_NAME} && cd ${REAL_PACKAGE_NAME} && git checkout -b build ${PACKAGE_COMMIT}

steps:
- cd ${REAL_PACKAGE_NAME} && ./configure --prefix=/usr
- cd ${REAL_PACKAGE_NAME} && make -j8
- cd ${REAL_PACKAGE_NAME} && make DESTDIR=/${REAL_PACKAGE_NAME} install
- cd ${REAL_PACKAGE_NAME} && make install
