requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
- category: "utils"
  name: "libarchive"
  version: ">=0"
env:
- CFLAGS="-I/include -I/usr/include -static -fPIC"
- CPPFLAGS="-I/include -I/usr/include -static -fPIC"
- FIRMWAREDIR="/lib/firmware"
package_dir: /{{.Values.name}}
prelude:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf utils/curl libs/zlib vcs/git development/automake development/pkg-config development/m4 \
   development/make system/musl-toolchain && \
   luet install libs/gettext-tools && \
   curl -L https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-${PACKAGE_VERSION}.{{.Values.archive_format}} -o {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.archive_format}} && \
   tar -xvf {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.archive_format}} -C ./ && mv {{.Values.name}}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   mkdir -p /${PACKAGE_NAME}
steps:
- |
   cd ${PACKAGE_NAME} && \
   make DESTDIR=/${PACKAGE_NAME} && \
   make DESTDIR=/${PACKAGE_NAME} install && make install
