requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
- category: "libs"
  name: "libxml2"
  version: ">=0"
- category: "libs"
  name: "libxslt"
  version: ">=0"

env:
- CFLAGS="-g -O2 -I/include -I/usr/include -static"
- CPPFLAGS="-I/include -I/usr/include -static"
- LUET_PACKAGES="lang/python vcs/git shells/bash development/libtool libs/libressl development/make development/pkg-config libs/zlib development/m4 shells/bash utils/autoconf development/automake system/musl-compat utils/file"

package_dir: /asciidoc
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/ && \
   luet install ${LUET_PACKAGES} && \
   git clone https://github.com/asciidoc/asciidoc-py3 ${PACKAGE_NAME} && cd ${PACKAGE_NAME} && git checkout -b build ${PACKAGE_VERSION}
- cd ${PACKAGE_NAME} && sed -i 's/--nonet//g' a2x.py
- cd ${PACKAGE_NAME} && sed -i 's/--noout//g' a2x.py

steps:
- cd ${PACKAGE_NAME} && autoconf
- cd ${PACKAGE_NAME} && ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR="/${PACKAGE_NAME}" install
- cd ${PACKAGE_NAME} && make install
