requires:
- category: "development"
  name: "toolchain"
  version: ">=0"


env:
- CFLAGS="-I/include -I/usr/include -static"
- LDFLAGS="-L/usr/lib -L/lib"
- CC=gcc
package_dir: /{{.Values.name}}
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf utils/curl development/make development/automake vcs/git development/m4 libs/libressl && \
   mkdir -p /${PACKAGE_NAME} && \
   curl -L https://github.com/alpinelinux/$PACKAGE_NAME/archive/$PACKAGE_VERSION.tar.gz -o ${PACKAGE_NAME}.tar.gz && tar xvf ${PACKAGE_NAME}.tar.gz  && \
   mv ${PACKAGE_NAME}-$PACKAGE_VERSION $PACKAGE_NAME 

steps:
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install