image: alpine
env:
  #- CGO_ENABLED=0
- GOPATH=/gopath

package_dir: /clr-installer
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME} && \
   apk add git go gtk+3.0-dev cairo-dev glib-dev coreutils make && \
   git clone https://github.com/clearlinux/clr-installer clr-installer && cd clr-installer && git checkout -b build ${PACKAGE_VERSION}

steps:
- mkdir $GOPATH
- go get github.com/gotk3/gotk3/cairo
- cp -rfv custom/* ${PACKAGE_NAME}
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install
- cd ${PACKAGE_NAME} && make install
