requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
- name: rsync
  category: utils
  version: ">=0"
package_dir: /{{.Values.name}}
prelude:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*}  && \
   set -x && \
   luet install utils/autoconf utils/curl libs/zlib vcs/git development/automake development/patch development/pkg-config development/libtool development/m4 lang/perl \
   development/make system/musl-toolchain && \
   luet install libs/gettext-tools && \
   curl -L https://cdn.kernel.org/pub/linux/kernel/v${PACKAGE_VERSION:0:1}.x/linux-${PACKAGE_VERSION}.{{.Values.archive_format}} -o {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.archive_format}} && \
   tar -xvf {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.archive_format}} -C ./ && mv linux-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   mkdir -p /${PACKAGE_NAME} && cd ${PACKAGE_NAME}

steps:
- |
   cd ${PACKAGE_NAME} && \
   make headers_install INSTALL_HDR_PATH="/${PACKAGE_NAME}/usr" && \
   make headers_install
