requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
- category: "libs"
  name: "ncurses"
  version: ">=0"
- category: "development"
  name: "linux-headers"
  version: ">=0"
env:
- CFLAGS="-I/include -I/usr/include -static -fPIC"
- CPPFLAGS="-I/include -I/usr/include -static -fPIC"

package_dir: /{{.Values.name}}
prelude:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf utils/curl lang/python libs/zlib vcs/git development/automake development/pkg-config development/m4 \
   development/make system/musl-toolchain && \
   luet install libs/gettext-tools && \
   curl -L https://github.com/htop-dev/htop/archive/${PACKAGE_VERSION}.{{.Values.archive_format}} -o {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.archive_format}} && \
   tar -xvf {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.archive_format}} -C ./ && mv {{.Values.name}}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   mkdir -p /${PACKAGE_NAME}
steps:
- |
   cd ${PACKAGE_NAME} && \
   ./autogen.sh && \
   ./configure --prefix=/usr \
   --sysconfdir=/etc \
   --mandir=/usr/share/man \
   --localstatedir=/var \
   --enable-cgroup \
   --enable-taskstats && \
   make DESTDIR=/${PACKAGE_NAME} && \
   make DESTDIR=/${PACKAGE_NAME} install && make install
