requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

env:
- CFLAGS="-I/include -I/usr/include"

package_dir: /skalibs
prelude:
- |
   mkdir -p /${PACKAGE_NAME} && \
   luet install shells/bash development/make utils/ca-certificates libs/libressl vcs/git && \
   git clone https://github.com/skarnet/skalibs && cd skalibs && git checkout -b build v${PACKAGE_VERSION%\+*}

steps:
- cd ${PACKAGE_NAME} && ./configure
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install
- cd ${PACKAGE_NAME} && make install
