requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
prelude:
- luet install lang/go
- mkdir -p /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}
- cd /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }} && git clone https://github.com/{{ ( index .Values.labels  "github.repo" ) }}/{{.Values.name}}
env:
- GOPATH=/go
- LUET_YES=true
steps:
- |
  cd /go/src/github.com/{{ ( index .Values.labels "github.repo" ) }}/{{.Values.name}} && \
  git checkout v{{ ( index .Values.labels "original.package.version" ) }} && \
  CC=${MUSL_TARGET}-gcc make {{.Values.name}} && \
  mv {{.Values.name}} /usr/bin/{{.Values.name}}
includes:
- /usr/bin/{{.Values.name}}
