requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
- name: libnftnl
  category: libs
  version: ">=0"
- name: "libmnl"
  category: "libs"
  version: ">=0"

env:
- CFLAGS="-D_GNU_SOURCE -I/include -I/usr/include -fPIC"
- LDFLAGS="-L/usr/lib -L/lib"

package_dir: /{{.Values.name}}
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf development/make development/automake vcs/git development/m4 libs/libressl && \
   mkdir -p /${PACKAGE_NAME} && mkdir ${PACKAGE_NAME} && \
   wget https://www.netfilter.org/projects/iptables/files/iptables-${PACKAGE_VERSION}.tar.bz2 -O iptables.tar.bz2 && tar -xvf iptables.tar.bz2 -C ./ && mv iptables-$PACKAGE_VERSION ${PACKAGE_NAME}
steps:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   cd ${PACKAGE_NAME}/${PACKAGE_NAME}-$PACKAGE_VERSION && \
   ./configure --prefix=/usr --without-kernel --enable-devel --enable-libipq --enable-shared --sbindir=/sbin  && \
   sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool && \
   sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool && \
   make -j8  && \
   make DESTDIR=/${PACKAGE_NAME} install && \
   cp -rfv include "/${PACKAGE_NAME}"/usr
