requires:
- category: "libs"
  name: "ncurses"
  version: ">=0"

package_dir: /{{.Values.name}}
prelude:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf utils/curl libs/zlib vcs/git development/automake development/pkg-config development/m4 \
   development/make system/musl-toolchain && \
   luet install libs/gettext-tools && \
   curl -L http://www.nano-editor.org/dist/v${PACKAGE_VERSION%.*}/{{.Values.name}}-${PACKAGE_VERSION}.tar.gz -o {{.Values.name}}-${PACKAGE_VERSION}.tar.gz && \
   tar -xvf {{.Values.name}}-${PACKAGE_VERSION}.tar.gz -C ./ && mv {{.Values.name}}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   mkdir -p /${PACKAGE_NAME}

steps:
- |
   cd ${PACKAGE_NAME} && \
   ./configure --prefix=/usr && \
   make DESTDIR=/${PACKAGE_NAME} && \
   make DESTDIR=/${PACKAGE_NAME} install && make install
