requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
- category: "libs"
  name: "libxslt"
  version: ">=0"

env:
- CFLAGS="-g -O2 -I/include -I/usr/include -static -fPIC"
- CPPFLAGS="-I/include -I/usr/include -static -fPIC"

package_dir: /musl-fts
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/ && \
   luet install vcs/git shells/bash development/libtool development/musl-utils libs/libressl development/make development/pkg-config libs/zlib development/m4 shells/bash utils/autoconf development/automake && \
   git clone https://github.com/void-linux/musl-fts && cd ${PACKAGE_NAME} && git checkout -b build v${PACKAGE_VERSION}

steps:
- cd ${PACKAGE_NAME} && ./bootstrap.sh
- cd ${PACKAGE_NAME} && ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib --disable-dependency-tracking --with-openssl --with-zlib
- cd ${PACKAGE_NAME} && make -j8
- cd ${PACKAGE_NAME} && make DESTDIR="/${PACKAGE_NAME}" install
- cd ${PACKAGE_NAME} && make install
