requires: {{.Values.build_requires | toYaml | nindent 1}}

env:
- CFLAGS="-g -O2 -I/include -I/usr/include -I/usr/include/X11 -static"
- CPPFLAGS="-I/include -I/usr/include -I/usr/include/X11 -static"
package_dir: /{{.Values.name}}
prelude:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install libs/zlib utils/autoconf utils/curl libs/zlib vcs/git development/automake development/pkg-config development/m4 lang/python \
   development/make system/musl-toolchain && \
   curl -L {{.Values.base_url}}{{.Values.name}}-$PACKAGE_VERSION.{{.Values.extension}} -o {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.extension}} && \
   tar -xvf {{.Values.name}}-${PACKAGE_VERSION}.{{.Values.extension}} -C ./ && mv {{.Values.name}}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   mkdir -p /${PACKAGE_NAME}

steps:
- |
   cd ${PACKAGE_NAME} && \
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var && \
   make DESTDIR=/${PACKAGE_NAME} && \
   make DESTDIR=/${PACKAGE_NAME} install && make install
