image: quay.io/mocaccino/extra
package_dir: /{{ .Values.name }}
env:
{{- if .Values.group }}
- ENTITY_GROUP=/{{ .Values.name}}/etc/entities/{{ .Values.name }}/group.yaml
{{- end}}
- ENTITY_USER=/{{ .Values.name}}/etc/entities/{{ .Values.name }}/user.yaml

- LUET_YES=true
steps:
- luet install utils/yq
- mkdir -p /{{ .Values.name }}/etc/entities/{{ .Values.name }}
{{- if .Values.group }}
- touch $ENTITY_GROUP
- yq w -i $ENTITY_GROUP gid {{.Values.gid}}
- yq w -i ${ENTITY_GROUP} kind group
- yq w -i ${ENTITY_GROUP} group_name {{ .Values.name }}
- yq w -i ${ENTITY_GROUP} users {{ .Values.name }}
{{- end }}
- touch $ENTITY_USER
- yq w -i $ENTITY_USER uid {{.Values.uid}}
- yq w -i $ENTITY_USER gid {{.Values.gid}}
- yq w -i ${ENTITY_USER} kind user
- yq w -i ${ENTITY_USER} username /{{ .Values.name }}
- yq w -i ${ENTITY_USER} password x
- yq w -i $ENTITY_USER shell {{.Values.shell}}
